name: ci-cd-pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r payment-processing-service/requirements.txt
      - name: Run tests
        run: pytest payment-processing-service/
      - name: Build Docker image
        run: docker build -t payment-processing-service:latest ./payment-processing-service
      # Add steps for push to registry and deploy to EKS as needed
